language: cpp
before_install:
    - sudo add-apt-repository ppa:openjdk-r/ppa
    - sudo apt-get update
install:
    - sudo apt-get install openjdk-8-jdk
    - sudo apt-get install libboost1.55-dev boost1.55
    - sudo apt-get install maven
    - sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
script:
    - ./build
