language: cpp
install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:openjdk-r/ppa
    - sudo add-apt-repository -y ppa:boost-latest/ppa # only 12.04
    - sudo add-apt-repository -y ppa:ubuntu-lxc/stable
    #- sudo add-apt-repository -y ppa:george-edison55/cmake-3.x # only 14.04
    - sudo apt-get update -q
    - sudo apt-get install openjdk-8-jdk
    - sudo apt-get install libboost1.55-dev boost1.55
    - sudo apt-get install maven
    - sudo apt-get install g++-4.9 gcc-4.9
    #- sudo apt-get install cmake # only 14.04
    - sudo apt-get install lxc-dev lxc
    - sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
    - sudo wget http://www.cmake.org/files/v3.2/cmake-3.2.2-Linux-x86_64.tar.gz # only 12.04
    - sudo tar xf cmake-3.2.2-Linux-x86_64.tar.gz # only 12.04
    - sudo cp -r cmake-3.2.2-Linux-x86_64/* /usr # only 12.04
    - 'echo export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 > /etc/profile.d/java.sh'
script:
    - ./build
